// <auto-generated />
using System;
using EntregaSegura.Repository.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EntregaSegura.API.Migrations
{
    [DbContext(typeof(EntregaSeguraContext))]
    [Migration("20230506222547_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EntregaSegura.Entities.Models.Condominio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CND_ID")
                        .HasColumnOrder(1)
                        .HasComment("Chave primária do condomínio");

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasColumnType("varchar(14)")
                        .HasColumnName("CND_CNPJ")
                        .HasColumnOrder(3)
                        .HasComment("CNPJ do condomínio");

                    b.Property<DateTime>("DataAtualizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("CND_DATA_ATUALIZACAO")
                        .HasColumnOrder(7)
                        .HasDefaultValueSql("GETDATE()")
                        .HasComment("Data da última atualização do condomínio");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("CND_DATA_CRIACAO")
                        .HasColumnOrder(6)
                        .HasDefaultValueSql("GETDATE()")
                        .HasComment("Data de criação do condomínio");

                    b.Property<DateTime?>("DataExclusao")
                        .HasColumnType("datetime")
                        .HasColumnName("CND_DATA_EXCLUSAO")
                        .HasColumnOrder(8)
                        .HasComment("Data da exclusão do condomínio");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("CND_EMAIL")
                        .HasColumnOrder(5)
                        .HasComment("E-mail do condomínio");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("CND_NOME")
                        .HasColumnOrder(2)
                        .HasComment("Nome do condomínio");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("varchar(11)")
                        .HasColumnName("CND_TELEFONE")
                        .HasColumnOrder(4)
                        .HasComment("Telefone do condomínio");

                    b.HasKey("Id")
                        .HasName("PK_CONDOMINIOS");

                    b.HasIndex("CNPJ")
                        .IsUnique()
                        .HasDatabaseName("IX_CONDOMINIOS_CNPJ");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_CONDOMINIOS_EMAIL");

                    b.HasIndex("Nome")
                        .IsUnique()
                        .HasDatabaseName("IX_CONDOMINIOS_NOME");

                    b.ToTable("TB_CONDOMINIOS", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("502baf2c-f36a-4e7d-a535-da632f982172"),
                            CNPJ = "11111111111111",
                            DataAtualizacao = new DateTime(2023, 5, 6, 19, 25, 47, 112, DateTimeKind.Local).AddTicks(3107),
                            DataCriacao = new DateTime(2023, 5, 6, 19, 25, 47, 112, DateTimeKind.Local).AddTicks(3097),
                            Email = "contato@condominioexemplo.com.br",
                            Nome = "Condomínio Exemplo",
                            Telefone = "11999999999"
                        });
                });

            modelBuilder.Entity("EntregaSegura.Entities.Models.Endereco", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("END_ID")
                        .HasColumnOrder(1)
                        .HasComment("Chave primária do endereço");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("END_BAIRRO")
                        .HasColumnOrder(7)
                        .HasComment("Bairro do endereço");

                    b.Property<string>("CEP")
                        .IsRequired()
                        .HasColumnType("varchar(8)")
                        .HasColumnName("END_CEP")
                        .HasColumnOrder(6)
                        .HasComment("CEP do endereço");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("END_CIDADE")
                        .HasColumnOrder(8)
                        .HasComment("Cidade do endereço");

                    b.Property<string>("Complemento")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("END_COMPLEMENTO")
                        .HasColumnOrder(5)
                        .HasComment("Complemento do endereço");

                    b.Property<Guid>("CondominioId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CON_ID")
                        .HasColumnOrder(2)
                        .HasComment("Chave estrangeira do condomínio");

                    b.Property<DateTime>("DataAtualizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("END_DATA_ATUALIZACAO")
                        .HasColumnOrder(11)
                        .HasDefaultValueSql("GETDATE()")
                        .HasComment("Data da última atualização do endereço");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("END_DATA_CRIACAO")
                        .HasColumnOrder(10)
                        .HasDefaultValueSql("GETDATE()")
                        .HasComment("Data de criação do endereço");

                    b.Property<DateTime?>("DataExclusao")
                        .HasColumnType("datetime")
                        .HasColumnName("END_DATA_EXCLUSAO")
                        .HasColumnOrder(12)
                        .HasComment("Data da exclusão do endereço");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("varchar(2)")
                        .HasColumnName("END_ESTADO")
                        .HasColumnOrder(9)
                        .HasComment("Estado do endereço");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("END_LOGRADOURO")
                        .HasColumnOrder(3)
                        .HasComment("Logradouro do endereço");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("END_NUMERO")
                        .HasColumnOrder(4)
                        .HasComment("Número do endereço");

                    b.HasKey("Id")
                        .HasName("PK_ENDERECOS");

                    b.HasIndex("CEP")
                        .HasDatabaseName("IX_ENDERECO_CEP");

                    b.HasIndex("CondominioId")
                        .IsUnique()
                        .HasDatabaseName("IX_ENDERECO_CONDOMINIO");

                    b.ToTable("TB_ENDERECOS", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("87e884bf-2426-414c-8679-3d0632dc10d6"),
                            Bairro = "Bairro Exemplo",
                            CEP = "11111111",
                            Cidade = "Cidade Exemplo",
                            Complemento = "Bloco A",
                            CondominioId = new Guid("502baf2c-f36a-4e7d-a535-da632f982172"),
                            DataAtualizacao = new DateTime(2023, 5, 6, 19, 25, 47, 112, DateTimeKind.Local).AddTicks(3214),
                            DataCriacao = new DateTime(2023, 5, 6, 19, 25, 47, 112, DateTimeKind.Local).AddTicks(3214),
                            Estado = "SP",
                            Logradouro = "Rua Exemplo",
                            Numero = "100"
                        });
                });

            modelBuilder.Entity("EntregaSegura.Entities.Models.Entrega", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ETG_ID")
                        .HasColumnOrder(1)
                        .HasComment("Chave primária da entrega");

                    b.Property<DateTime>("DataAtualizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("ETG_DATA_ATUALIZACAO")
                        .HasColumnOrder(13)
                        .HasDefaultValueSql("GETDATE()")
                        .HasComment("Data da última atualização da entrega");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("ETG_DATA_CRIACAO")
                        .HasColumnOrder(12)
                        .HasDefaultValueSql("GETDATE()")
                        .HasComment("Data de criação da entrega");

                    b.Property<DateTime?>("DataExclusao")
                        .HasColumnType("datetime")
                        .HasColumnName("ETG_DATA_EXCLUSAO")
                        .HasColumnOrder(14)
                        .HasComment("Data da exclusão da entrega");

                    b.Property<DateTime>("DataRecebimento")
                        .HasColumnType("datetime")
                        .HasColumnName("ETG_DATA_RECEBIMENTO")
                        .HasColumnOrder(7)
                        .HasComment("Data de recebimento da entrega");

                    b.Property<DateTime?>("DataRetirada")
                        .HasColumnType("datetime")
                        .HasColumnName("ETG_DATA_RETIRADA")
                        .HasColumnOrder(8)
                        .HasComment("Data de retirada da entrega");

                    b.Property<string>("Descricao")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("ETG_DESCRICAO")
                        .HasColumnOrder(9)
                        .HasComment("Descrição da entrega");

                    b.Property<string>("Destinatario")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("ETG_DESTINATARIO")
                        .HasColumnOrder(6)
                        .HasComment("Nome do destinatário da entrega");

                    b.Property<Guid>("FuncionarioId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("FUN_ID")
                        .HasColumnOrder(3)
                        .HasComment("Chave estrangeira do funcionário");

                    b.Property<Guid>("MoradorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MOR_ID")
                        .HasColumnOrder(4)
                        .HasComment("Chave estrangeira do morador");

                    b.Property<string>("Observacao")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("ETG_OBSERVACAO")
                        .HasColumnOrder(10)
                        .HasComment("Observação da entrega");

                    b.Property<string>("Remetente")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("ETG_REMETENTE")
                        .HasColumnOrder(5)
                        .HasComment("Nome do remetente da entrega");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("ETG_STATUS")
                        .HasColumnOrder(11)
                        .HasComment("Status da entrega");

                    b.Property<Guid>("TransportadoraId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TRP_ID")
                        .HasColumnOrder(2)
                        .HasComment("Chave estrangeira da transportadora");

                    b.HasKey("Id")
                        .HasName("PK_ENTREGAS");

                    b.HasIndex("FuncionarioId");

                    b.HasIndex("MoradorId");

                    b.HasIndex("TransportadoraId");

                    b.ToTable("TB_ENTREGAS", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("cbd10c3c-b8ac-4dbe-ab91-c0277716bc49"),
                            DataAtualizacao = new DateTime(2023, 5, 6, 19, 25, 47, 112, DateTimeKind.Local).AddTicks(3364),
                            DataCriacao = new DateTime(2023, 5, 6, 19, 25, 47, 112, DateTimeKind.Local).AddTicks(3364),
                            DataRecebimento = new DateTime(2023, 5, 6, 19, 25, 47, 112, DateTimeKind.Local).AddTicks(3366),
                            Descricao = "Descrição da entrega",
                            Destinatario = "Destinatario Exemplo",
                            FuncionarioId = new Guid("e0024df7-457a-44b7-bf34-929d65e1981e"),
                            MoradorId = new Guid("5e71fa02-7271-49be-8c41-9cf04a8eb471"),
                            Observacao = "Observação da entrega",
                            Remetente = "Remetente Exemplo",
                            Status = 1,
                            TransportadoraId = new Guid("2ede059b-6321-4ead-aef3-01040f1c36b5")
                        });
                });

            modelBuilder.Entity("EntregaSegura.Entities.Models.Funcionario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("FUN_ID")
                        .HasColumnOrder(1)
                        .HasComment("Chave primária do funcionário");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("varchar(11)")
                        .HasColumnName("FUN_CPF")
                        .HasColumnOrder(3)
                        .HasComment("CPF do funcionário");

                    b.Property<int>("Cargo")
                        .HasColumnType("int")
                        .HasColumnName("FUN_CARGO")
                        .HasColumnOrder(7)
                        .HasComment("Cargo do funcionário");

                    b.Property<Guid>("CondominioId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("FUN_CONDOMINIO_ID")
                        .HasColumnOrder(13)
                        .HasComment("Chave estrangeira do condomínio");

                    b.Property<DateTime>("DataAdmissao")
                        .HasColumnType("datetime")
                        .HasColumnName("FUN_DATA_ADMISSAO")
                        .HasColumnOrder(8)
                        .HasComment("Data de admissão do funcionário");

                    b.Property<DateTime>("DataAtualizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("FUN_DATA_ATUALIZACAO")
                        .HasColumnOrder(11)
                        .HasDefaultValueSql("GETDATE()")
                        .HasComment("Data da última atualização do funcionário");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("FUN_DATA_CRIACAO")
                        .HasColumnOrder(10)
                        .HasDefaultValueSql("GETDATE()")
                        .HasComment("Data de criação do funcionário");

                    b.Property<DateTime?>("DataDemissao")
                        .HasColumnType("datetime")
                        .HasColumnName("FUN_DATA_DEMISSAO")
                        .HasColumnOrder(9)
                        .HasComment("Data de demissão do funcionário");

                    b.Property<DateTime?>("DataExclusao")
                        .HasColumnType("datetime")
                        .HasColumnName("FUN_DATA_EXCLUSAO")
                        .HasColumnOrder(12)
                        .HasComment("Data da exclusão do funcionário");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("FUN_EMAIL")
                        .HasColumnOrder(4)
                        .HasComment("Email do funcionário");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("FUN_NOME")
                        .HasColumnOrder(2)
                        .HasComment("Nome do funcionário");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("FUN_STATUS")
                        .HasColumnOrder(6)
                        .HasComment("Status do funcionário");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("varchar(11)")
                        .HasColumnName("FUN_TELEFONE")
                        .HasColumnOrder(5)
                        .HasComment("Telefone do funcionário");

                    b.HasKey("Id")
                        .HasName("PK_FUNCIONARIOS");

                    b.HasIndex("CPF")
                        .IsUnique()
                        .HasDatabaseName("IX_FUNCIONARIO_CPF");

                    b.HasIndex("CondominioId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_FUNCIONARIO_EMAIL");

                    b.ToTable("TB_FUNCIONARIOS", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("e0024df7-457a-44b7-bf34-929d65e1981e"),
                            CPF = "98765432109",
                            Cargo = 2,
                            CondominioId = new Guid("502baf2c-f36a-4e7d-a535-da632f982172"),
                            DataAdmissao = new DateTime(2023, 5, 6, 19, 25, 47, 112, DateTimeKind.Local).AddTicks(3329),
                            DataAtualizacao = new DateTime(2023, 5, 6, 19, 25, 47, 112, DateTimeKind.Local).AddTicks(3329),
                            DataCriacao = new DateTime(2023, 5, 6, 19, 25, 47, 112, DateTimeKind.Local).AddTicks(3328),
                            Email = "funcionario@email.com",
                            Nome = "Funcionario Exemplo",
                            Status = 2,
                            Telefone = "11999999999"
                        });
                });

            modelBuilder.Entity("EntregaSegura.Entities.Models.Morador", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MOR_ID")
                        .HasColumnOrder(1)
                        .HasComment("Chave primária do morador");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("varchar(11)")
                        .HasColumnName("MOR_CPF")
                        .HasColumnOrder(3)
                        .HasComment("CPF do morador");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("datetime")
                        .HasColumnName("MOR_DATA_ATUALIZACAO")
                        .HasColumnOrder(9)
                        .HasComment("Data da última atualização do morador");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime")
                        .HasColumnName("MOR_DATA_CRIACAO")
                        .HasColumnOrder(8)
                        .HasComment("Data de criação do morador");

                    b.Property<DateTime?>("DataExclusao")
                        .HasColumnType("datetime")
                        .HasColumnName("MOR_DATA_EXCLUSAO")
                        .HasColumnOrder(10)
                        .HasComment("Data da exclusão do morador");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("MOR_EMAIL")
                        .HasColumnOrder(4)
                        .HasComment("Email do morador");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("MOR_NOME")
                        .HasColumnOrder(2)
                        .HasComment("Nome do morador");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("MOR_STATUS")
                        .HasColumnOrder(6)
                        .HasComment("Status do morador");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("varchar(11)")
                        .HasColumnName("MOR_TELEFONE")
                        .HasColumnOrder(5)
                        .HasComment("Telefone do morador");

                    b.Property<Guid>("UnidadeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MOR_UNIDADE_ID")
                        .HasColumnOrder(7)
                        .HasComment("Chave estrangeira da unidade do morador");

                    b.HasKey("Id")
                        .HasName("PK_MORADORES");

                    b.HasIndex("CPF")
                        .IsUnique()
                        .HasDatabaseName("IX_MORADORES_CPF");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_MORADORES_EMAIL");

                    b.HasIndex("UnidadeId")
                        .HasDatabaseName("IX_MORADORES_UNIDADE_ID");

                    b.ToTable("TB_MORADORES", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("5e71fa02-7271-49be-8c41-9cf04a8eb471"),
                            CPF = "12345678901",
                            DataAtualizacao = new DateTime(2023, 5, 6, 19, 25, 47, 112, DateTimeKind.Local).AddTicks(3312),
                            DataCriacao = new DateTime(2023, 5, 6, 19, 25, 47, 112, DateTimeKind.Local).AddTicks(3311),
                            Email = "morador@email.com",
                            Nome = "Morador Exemplo",
                            Status = 2,
                            Telefone = "11999999999",
                            UnidadeId = new Guid("085671e6-cea0-4cbb-a2f2-5ac83b7cc4e3")
                        });
                });

            modelBuilder.Entity("EntregaSegura.Entities.Models.Transportadora", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TRA_ID")
                        .HasColumnOrder(1)
                        .HasComment("Chave primária da transportadora");

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasColumnType("varchar(14)")
                        .HasColumnName("TRA_CNPJ")
                        .HasColumnOrder(3)
                        .HasComment("CNPJ da transportadora");

                    b.Property<DateTime>("DataAtualizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("TRA_DATA_ATUALIZACAO")
                        .HasColumnOrder(7)
                        .HasDefaultValueSql("GETDATE()")
                        .HasComment("Data da última atualização da transportadora");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("TRA_DATA_CRIACAO")
                        .HasColumnOrder(6)
                        .HasDefaultValueSql("GETDATE()")
                        .HasComment("Data de criação da transportadora");

                    b.Property<DateTime?>("DataExclusao")
                        .HasColumnType("datetime")
                        .HasColumnName("TRA_DATA_EXCLUSAO")
                        .HasColumnOrder(8)
                        .HasComment("Data da exclusão da transportadora");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("TRA_EMAIL")
                        .HasColumnOrder(5)
                        .HasComment("E-mail da transportadora");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("TRA_NOME")
                        .HasColumnOrder(2)
                        .HasComment("Nome da transportadora");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("varchar(11)")
                        .HasColumnName("TRA_TELEFONE")
                        .HasColumnOrder(4)
                        .HasComment("Telefone da transportadora");

                    b.HasKey("Id")
                        .HasName("PK_TRANSPORTADORAS");

                    b.HasIndex("CNPJ")
                        .IsUnique()
                        .HasDatabaseName("IX_TRANSPORTADORAS_CNPJ");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_TRANSPORTADORAS_EMAIL");

                    b.HasIndex("Nome")
                        .IsUnique()
                        .HasDatabaseName("IX_TRANSPORTADORAS_NOME");

                    b.HasIndex("Telefone")
                        .IsUnique()
                        .HasDatabaseName("IX_TRANSPORTADORAS_TELEFONE");

                    b.ToTable("TB_TRANSPORTADORAS", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("2ede059b-6321-4ead-aef3-01040f1c36b5"),
                            CNPJ = "22222222222222",
                            DataAtualizacao = new DateTime(2023, 5, 6, 19, 25, 47, 112, DateTimeKind.Local).AddTicks(3343),
                            DataCriacao = new DateTime(2023, 5, 6, 19, 25, 47, 112, DateTimeKind.Local).AddTicks(3343),
                            Email = "contato@transportadoraexemplo.com.br",
                            Nome = "Transportadora Exemplo",
                            Telefone = "11988888888"
                        });
                });

            modelBuilder.Entity("EntregaSegura.Entities.Models.Unidade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UND_ID")
                        .HasColumnOrder(1)
                        .HasComment("Chave primária da unidade");

                    b.Property<string>("Bloco")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("UND_BLOCO")
                        .HasColumnOrder(4)
                        .HasComment("Bloco da unidade");

                    b.Property<Guid>("CondominioId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CON_ID")
                        .HasColumnOrder(2)
                        .HasComment("Chave estrangeira do condomínio");

                    b.Property<DateTime>("DataAtualizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("UND_DATA_ATUALIZACAO")
                        .HasColumnOrder(6)
                        .HasDefaultValueSql("GETDATE()")
                        .HasComment("Data da última atualização da unidade");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("UND_DATA_CRIACAO")
                        .HasColumnOrder(5)
                        .HasDefaultValueSql("GETDATE()")
                        .HasComment("Data de criação da unidade");

                    b.Property<DateTime?>("DataExclusao")
                        .HasColumnType("datetime")
                        .HasColumnName("UND_DATA_EXCLUSAO")
                        .HasColumnOrder(7)
                        .HasComment("Data da exclusão da unidade");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("UND_NUMERO")
                        .HasColumnOrder(3)
                        .HasComment("Número da unidade");

                    b.HasKey("Id")
                        .HasName("PK_UNIDADES");

                    b.HasIndex("CondominioId", "Numero", "Bloco")
                        .IsUnique()
                        .HasDatabaseName("IX_UNIDADES_CONDOMINIO_NUMERO_BLOCO")
                        .HasFilter("[UND_BLOCO] IS NOT NULL");

                    b.ToTable("TB_UNIDADES", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("085671e6-cea0-4cbb-a2f2-5ac83b7cc4e3"),
                            Bloco = "A",
                            CondominioId = new Guid("502baf2c-f36a-4e7d-a535-da632f982172"),
                            DataAtualizacao = new DateTime(2023, 5, 6, 19, 25, 47, 112, DateTimeKind.Local).AddTicks(3293),
                            DataCriacao = new DateTime(2023, 5, 6, 19, 25, 47, 112, DateTimeKind.Local).AddTicks(3293),
                            Numero = "101"
                        });
                });

            modelBuilder.Entity("EntregaSegura.Entities.Models.Endereco", b =>
                {
                    b.HasOne("EntregaSegura.Entities.Models.Condominio", "Condominio")
                        .WithOne("Endereco")
                        .HasForeignKey("EntregaSegura.Entities.Models.Endereco", "CondominioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ENDERECO_CONDOMINIO");

                    b.Navigation("Condominio");
                });

            modelBuilder.Entity("EntregaSegura.Entities.Models.Entrega", b =>
                {
                    b.HasOne("EntregaSegura.Entities.Models.Funcionario", "Funcionario")
                        .WithMany("Entregas")
                        .HasForeignKey("FuncionarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_FUNCIONARIO_ENTREGA");

                    b.HasOne("EntregaSegura.Entities.Models.Morador", "Morador")
                        .WithMany("Entregas")
                        .HasForeignKey("MoradorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_MORADORES_ENTREGAS");

                    b.HasOne("EntregaSegura.Entities.Models.Transportadora", "Transportadora")
                        .WithMany("Entregas")
                        .HasForeignKey("TransportadoraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ENTREGA_TRANSPORTADORA");

                    b.Navigation("Funcionario");

                    b.Navigation("Morador");

                    b.Navigation("Transportadora");
                });

            modelBuilder.Entity("EntregaSegura.Entities.Models.Funcionario", b =>
                {
                    b.HasOne("EntregaSegura.Entities.Models.Condominio", "Condominio")
                        .WithMany("Funcionarios")
                        .HasForeignKey("CondominioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_FUNCIONARIO_CONDOMINIO");

                    b.Navigation("Condominio");
                });

            modelBuilder.Entity("EntregaSegura.Entities.Models.Morador", b =>
                {
                    b.HasOne("EntregaSegura.Entities.Models.Unidade", "Unidade")
                        .WithMany("Moradores")
                        .HasForeignKey("UnidadeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_MORADORES_UNIDADES");

                    b.Navigation("Unidade");
                });

            modelBuilder.Entity("EntregaSegura.Entities.Models.Unidade", b =>
                {
                    b.HasOne("EntregaSegura.Entities.Models.Condominio", "Condominio")
                        .WithMany("Unidades")
                        .HasForeignKey("CondominioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_UNIDADES_CONDOMINIOS");

                    b.Navigation("Condominio");
                });

            modelBuilder.Entity("EntregaSegura.Entities.Models.Condominio", b =>
                {
                    b.Navigation("Endereco");

                    b.Navigation("Funcionarios");

                    b.Navigation("Unidades");
                });

            modelBuilder.Entity("EntregaSegura.Entities.Models.Funcionario", b =>
                {
                    b.Navigation("Entregas");
                });

            modelBuilder.Entity("EntregaSegura.Entities.Models.Morador", b =>
                {
                    b.Navigation("Entregas");
                });

            modelBuilder.Entity("EntregaSegura.Entities.Models.Transportadora", b =>
                {
                    b.Navigation("Entregas");
                });

            modelBuilder.Entity("EntregaSegura.Entities.Models.Unidade", b =>
                {
                    b.Navigation("Moradores");
                });
#pragma warning restore 612, 618
        }
    }
}
