// <auto-generated />
using System;
using EntregaSegura.Repository.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EntregaSegura.API.Migrations
{
    [DbContext(typeof(EntregaSeguraContext))]
    partial class EntregaSeguraContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EntregaSegura.Entities.Models.Condominio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CND_ID")
                        .HasColumnOrder(1)
                        .HasComment("Chave primária do condomínio");

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("CND_CNPJ")
                        .HasColumnOrder(3)
                        .HasComment("CNPJ do condomínio");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("CND_DATA_CRIACAO")
                        .HasColumnOrder(6)
                        .HasDefaultValueSql("GETDATE()")
                        .HasComment("Data de criação do condomínio");

                    b.Property<DateTime?>("DataUltimaModificacao")
                        .HasColumnType("datetime")
                        .HasColumnName("CND_DATA_ULTIMA_MODIFICACAO")
                        .HasColumnOrder(7)
                        .HasComment("Data da última modificação do condomínio");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("CND_EMAIL")
                        .HasColumnOrder(5)
                        .HasComment("E-mail do condomínio");

                    b.Property<bool?>("Excluido")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("CND_EXCLUIDO")
                        .HasColumnOrder(8)
                        .HasComment("Flag que indica se o condomínio foi excluído");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("CND_NOME")
                        .HasColumnOrder(2)
                        .HasComment("Nome do condomínio");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("CND_TELEFONE")
                        .HasColumnOrder(4)
                        .HasComment("Telefone do condomínio");

                    b.HasKey("Id")
                        .HasName("PK_CONDOMINIOS");

                    b.HasIndex("CNPJ")
                        .IsUnique()
                        .HasDatabaseName("IX_CONDOMINIOS_CNPJ");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_CONDOMINIOS_EMAIL");

                    b.HasIndex("Nome")
                        .IsUnique()
                        .HasDatabaseName("IX_CONDOMINIOS_NOME");

                    b.ToTable("TB_CONDOMINIOS", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("e4e6af8b-8588-438b-9750-c45227c3aa92"),
                            CNPJ = "11111111111111",
                            DataCriacao = new DateTime(2023, 5, 2, 8, 5, 19, 210, DateTimeKind.Local).AddTicks(5694),
                            Email = "contato@condominioexemplo.com.br",
                            Nome = "Condomínio Exemplo",
                            Telefone = "11999999999"
                        });
                });

            modelBuilder.Entity("EntregaSegura.Entities.Models.Endereco", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("END_ID")
                        .HasColumnOrder(1)
                        .HasComment("Chave primária do endereço");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("END_BAIRRO")
                        .HasColumnOrder(7)
                        .HasComment("Bairro do endereço");

                    b.Property<string>("CEP")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("END_CEP")
                        .HasColumnOrder(6)
                        .HasComment("CEP do endereço");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("END_CIDADE")
                        .HasColumnOrder(8)
                        .HasComment("Cidade do endereço");

                    b.Property<string>("Complemento")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("END_COMPLEMENTO")
                        .HasColumnOrder(5)
                        .HasComment("Complemento do endereço");

                    b.Property<Guid>("CondominioId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CON_ID")
                        .HasColumnOrder(2)
                        .HasComment("Chave estrangeira do condomínio");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("END_DATA_CRIACAO")
                        .HasColumnOrder(10)
                        .HasDefaultValueSql("GETDATE()")
                        .HasComment("Data de criação do endereço");

                    b.Property<DateTime?>("DataUltimaModificacao")
                        .HasColumnType("datetime")
                        .HasColumnName("END_DATA_ULTIMA_MODIFICACAO")
                        .HasColumnOrder(11)
                        .HasComment("Data da última modificação do endereço");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("END_ESTADO")
                        .HasColumnOrder(9)
                        .HasComment("Estado do endereço");

                    b.Property<bool?>("Excluido")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("END_EXCLUIDO")
                        .HasColumnOrder(12)
                        .HasComment("Flag que indica se o endereço foi excluído");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("END_LOGRADOURO")
                        .HasColumnOrder(3)
                        .HasComment("Logradouro do endereço");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("END_NUMERO")
                        .HasColumnOrder(4)
                        .HasComment("Número do endereço");

                    b.HasKey("Id")
                        .HasName("PK_ENDERECOS");

                    b.HasIndex("CEP")
                        .HasDatabaseName("IX_ENDERECO_CEP");

                    b.HasIndex("CondominioId")
                        .IsUnique()
                        .HasDatabaseName("IX_ENDERECO_CONDOMINIO");

                    b.ToTable("TB_ENDERECOS", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("e51dbc58-a60f-4e88-9b47-d6893907eff4"),
                            Bairro = "Bairro Exemplo",
                            CEP = "11111111",
                            Cidade = "Cidade Exemplo",
                            Complemento = "Bloco A",
                            CondominioId = new Guid("e4e6af8b-8588-438b-9750-c45227c3aa92"),
                            DataCriacao = new DateTime(2023, 5, 2, 8, 5, 19, 210, DateTimeKind.Local).AddTicks(5818),
                            Estado = "SP",
                            Logradouro = "Rua Exemplo",
                            Numero = "100"
                        });
                });

            modelBuilder.Entity("EntregaSegura.Entities.Models.Entrega", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ETG_ID")
                        .HasColumnOrder(1)
                        .HasComment("Chave primária da entrega");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("ETG_DATA_CRIACAO")
                        .HasColumnOrder(13)
                        .HasDefaultValueSql("GETDATE()")
                        .HasComment("Data de criação da entrega");

                    b.Property<DateTime>("DataRecebimento")
                        .HasColumnType("datetime")
                        .HasColumnName("ETG_DATA_RECEBIMENTO")
                        .HasColumnOrder(8)
                        .HasComment("Data de recebimento da entrega");

                    b.Property<DateTime?>("DataRetirada")
                        .HasColumnType("datetime")
                        .HasColumnName("ETG_DATA_RETIRADA")
                        .HasColumnOrder(9)
                        .HasComment("Data de retirada da entrega");

                    b.Property<DateTime?>("DataUltimaModificacao")
                        .HasColumnType("datetime")
                        .HasColumnName("ETG_DATA_ULTIMA_MODIFICACAO")
                        .HasColumnOrder(14)
                        .HasComment("Data da última modificação da entrega");

                    b.Property<string>("Descricao")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("ETG_DESCRICAO")
                        .HasColumnOrder(10)
                        .HasComment("Descrição da entrega");

                    b.Property<string>("Destinatario")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("ETG_DESTINATARIO")
                        .HasColumnOrder(7)
                        .HasComment("Nome do destinatário da entrega");

                    b.Property<bool?>("Excluido")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("ETG_EXCLUIDO")
                        .HasColumnOrder(15)
                        .HasComment("Flag de exclusão da entrega");

                    b.Property<Guid>("FuncionarioId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("FUN_ID")
                        .HasColumnOrder(4)
                        .HasComment("Chave estrangeira do funcionário");

                    b.Property<Guid>("MoradorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MOR_ID")
                        .HasColumnOrder(5)
                        .HasComment("Chave estrangeira do morador");

                    b.Property<string>("Observacao")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("ETG_OBSERVACAO")
                        .HasColumnOrder(11)
                        .HasComment("Observação da entrega");

                    b.Property<string>("Remetente")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("ETG_REMETENTE")
                        .HasColumnOrder(6)
                        .HasComment("Nome do remetente da entrega");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("ETG_STATUS")
                        .HasColumnOrder(12)
                        .HasComment("Status da entrega");

                    b.Property<Guid>("TransportadoraId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TRP_ID")
                        .HasColumnOrder(2)
                        .HasComment("Chave estrangeira da transportadora");

                    b.Property<Guid>("UnidadeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UND_ID")
                        .HasColumnOrder(3)
                        .HasComment("Chave estrangeira da unidade");

                    b.HasKey("Id")
                        .HasName("PK_ENTREGAS");

                    b.HasIndex("FuncionarioId");

                    b.HasIndex("MoradorId");

                    b.HasIndex("TransportadoraId");

                    b.HasIndex("UnidadeId");

                    b.ToTable("TB_ENTREGAS", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1fe4de0-33e2-451a-a8ef-667e282e7f8a"),
                            DataCriacao = new DateTime(2023, 5, 2, 8, 5, 19, 210, DateTimeKind.Local).AddTicks(5922),
                            DataRecebimento = new DateTime(2023, 5, 2, 8, 5, 19, 210, DateTimeKind.Local).AddTicks(5923),
                            Descricao = "Descrição da entrega",
                            Destinatario = "Destinatario Exemplo",
                            FuncionarioId = new Guid("dc860e6a-2763-46ba-8912-2a7c79884c82"),
                            MoradorId = new Guid("a4dd6d7c-dc82-4de0-87ba-47060eedf07f"),
                            Observacao = "Observação da entrega",
                            Remetente = "Remetente Exemplo",
                            Status = 1,
                            TransportadoraId = new Guid("c7c480da-a12a-4620-8e46-56e1294dce20"),
                            UnidadeId = new Guid("e42af47c-24c2-4f83-a8cb-3cc95213ddc6")
                        });
                });

            modelBuilder.Entity("EntregaSegura.Entities.Models.Funcionario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("FUN_ID")
                        .HasColumnOrder(1)
                        .HasComment("Chave primária do funcionário");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("FUN_CPF")
                        .HasColumnOrder(3)
                        .HasComment("CPF do funcionário");

                    b.Property<int>("Cargo")
                        .HasColumnType("int")
                        .HasColumnName("FUN_CARGO")
                        .HasColumnOrder(7)
                        .HasComment("Cargo do funcionário");

                    b.Property<Guid>("CondominioId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("FUN_CONDOMINIO_ID")
                        .HasColumnOrder(13)
                        .HasComment("Chave estrangeira do condomínio");

                    b.Property<DateTime>("DataAdmissao")
                        .HasColumnType("datetime")
                        .HasColumnName("FUN_DATA_ADMISSAO")
                        .HasColumnOrder(8)
                        .HasComment("Data de admissão do funcionário");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("FUN_DATA_CRIACAO")
                        .HasColumnOrder(10)
                        .HasDefaultValueSql("GETDATE()")
                        .HasComment("Data de criação do funcionário");

                    b.Property<DateTime?>("DataDemissao")
                        .HasColumnType("datetime")
                        .HasColumnName("FUN_DATA_DEMISSAO")
                        .HasColumnOrder(9)
                        .HasComment("Data de demissão do funcionário");

                    b.Property<DateTime?>("DataUltimaModificacao")
                        .HasColumnType("datetime")
                        .HasColumnName("FUN_DATA_ULTIMA_MODIFICACAO")
                        .HasColumnOrder(11)
                        .HasComment("Data da última modificação do funcionário");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("FUN_EMAIL")
                        .HasColumnOrder(4)
                        .HasComment("Email do funcionário");

                    b.Property<bool?>("Excluido")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("FUN_EXCLUIDO")
                        .HasColumnOrder(12)
                        .HasComment("Flag que indica se o funcionário foi excluído");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("FUN_NOME")
                        .HasColumnOrder(2)
                        .HasComment("Nome do funcionário");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("FUN_STATUS")
                        .HasColumnOrder(6)
                        .HasComment("Status do funcionário");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("FUN_TELEFONE")
                        .HasColumnOrder(5)
                        .HasComment("Telefone do funcionário");

                    b.HasKey("Id")
                        .HasName("PK_FUNCIONARIOS");

                    b.HasIndex("CPF")
                        .IsUnique()
                        .HasDatabaseName("IX_FUNCIONARIO_CPF");

                    b.HasIndex("CondominioId");

                    b.ToTable("TB_FUNCIONARIOS", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("dc860e6a-2763-46ba-8912-2a7c79884c82"),
                            CPF = "98765432109",
                            Cargo = 2,
                            CondominioId = new Guid("e4e6af8b-8588-438b-9750-c45227c3aa92"),
                            DataAdmissao = new DateTime(2023, 5, 2, 8, 5, 19, 210, DateTimeKind.Local).AddTicks(5896),
                            DataCriacao = new DateTime(2023, 5, 2, 8, 5, 19, 210, DateTimeKind.Local).AddTicks(5895),
                            Email = "funcionario@email.com",
                            Nome = "Funcionario Exemplo",
                            Status = 2,
                            Telefone = "11999999999"
                        });
                });

            modelBuilder.Entity("EntregaSegura.Entities.Models.Morador", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MOR_ID")
                        .HasColumnOrder(1)
                        .HasComment("Chave primária do morador");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("MOR_CPF")
                        .HasColumnOrder(3)
                        .HasComment("CPF do morador");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime")
                        .HasColumnName("MOR_DATA_CRIACAO")
                        .HasColumnOrder(8)
                        .HasComment("Data de criação do morador");

                    b.Property<DateTime?>("DataUltimaModificacao")
                        .HasColumnType("datetime")
                        .HasColumnName("MOR_DATA_ULTIMA_MODIFICACAO")
                        .HasColumnOrder(9)
                        .HasComment("Data da última modificação do morador");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("MOR_EMAIL")
                        .HasColumnOrder(4)
                        .HasComment("Email do morador");

                    b.Property<bool?>("Excluido")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("MOR_EXCLUIDO")
                        .HasColumnOrder(10)
                        .HasComment("Flag que indica se o morador foi excluído");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("MOR_NOME")
                        .HasColumnOrder(2)
                        .HasComment("Nome do morador");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("MOR_STATUS")
                        .HasColumnOrder(6)
                        .HasComment("Status do morador");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("MOR_TELEFONE")
                        .HasColumnOrder(5)
                        .HasComment("Telefone do morador");

                    b.Property<Guid>("UnidadeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MOR_UNIDADE_ID")
                        .HasColumnOrder(7)
                        .HasComment("Chave estrangeira da unidade do morador");

                    b.HasKey("Id")
                        .HasName("PK_MORADORES");

                    b.HasIndex("CPF")
                        .IsUnique()
                        .HasDatabaseName("IX_MORADORES_CPF");

                    b.HasIndex("UnidadeId")
                        .HasDatabaseName("IX_MORADORES_UNIDADE_ID");

                    b.ToTable("TB_MORADORES", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a4dd6d7c-dc82-4de0-87ba-47060eedf07f"),
                            CPF = "12345678901",
                            DataCriacao = new DateTime(2023, 5, 2, 8, 5, 19, 210, DateTimeKind.Local).AddTicks(5884),
                            Email = "morador@email.com",
                            Nome = "Morador Exemplo",
                            Status = 2,
                            Telefone = "11999999999",
                            UnidadeId = new Guid("e42af47c-24c2-4f83-a8cb-3cc95213ddc6")
                        });
                });

            modelBuilder.Entity("EntregaSegura.Entities.Models.Transportadora", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TRA_ID")
                        .HasColumnOrder(1)
                        .HasComment("Chave primária da transportadora");

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("TRA_CNPJ")
                        .HasColumnOrder(3)
                        .HasComment("CNPJ da transportadora");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("TRA_DATA_CRIACAO")
                        .HasColumnOrder(6)
                        .HasDefaultValueSql("GETDATE()")
                        .HasComment("Data de criação da transportadora");

                    b.Property<DateTime?>("DataUltimaModificacao")
                        .HasColumnType("datetime")
                        .HasColumnName("TRA_DATA_ULTIMA_MODIFICACAO")
                        .HasColumnOrder(7)
                        .HasComment("Data da última modificação da transportadora");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("TRA_EMAIL")
                        .HasColumnOrder(5)
                        .HasComment("E-mail da transportadora");

                    b.Property<bool?>("Excluido")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasColumnName("TRA_EXCLUIDO")
                        .HasColumnOrder(8)
                        .HasDefaultValueSql("0")
                        .HasComment("Flag de exclusão da transportadora");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("TRA_NOME")
                        .HasColumnOrder(2)
                        .HasComment("Nome da transportadora");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("TRA_TELEFONE")
                        .HasColumnOrder(4)
                        .HasComment("Telefone da transportadora");

                    b.HasKey("Id")
                        .HasName("PK_TRANSPORTADORAS");

                    b.HasIndex("CNPJ")
                        .IsUnique()
                        .HasDatabaseName("IX_TRANSPORTADORAS_CNPJ");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_TRANSPORTADORAS_EMAIL");

                    b.HasIndex("Nome")
                        .IsUnique()
                        .HasDatabaseName("IX_TRANSPORTADORAS_NOME");

                    b.ToTable("TB_TRANSPORTADORAS", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c7c480da-a12a-4620-8e46-56e1294dce20"),
                            CNPJ = "22222222222222",
                            DataCriacao = new DateTime(2023, 5, 2, 8, 5, 19, 210, DateTimeKind.Local).AddTicks(5911),
                            Email = "contato@transportadoraexemplo.com.br",
                            Nome = "Transportadora Exemplo",
                            Telefone = "11988888888"
                        });
                });

            modelBuilder.Entity("EntregaSegura.Entities.Models.Unidade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UND_ID")
                        .HasColumnOrder(1)
                        .HasComment("Chave primária da unidade");

                    b.Property<string>("Bloco")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("UND_BLOCO")
                        .HasColumnOrder(4)
                        .HasComment("Bloco da unidade");

                    b.Property<Guid>("CondominioId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CON_ID")
                        .HasColumnOrder(2)
                        .HasComment("Chave estrangeira do condomínio");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("UND_DATA_CRIACAO")
                        .HasColumnOrder(5)
                        .HasDefaultValueSql("GETDATE()")
                        .HasComment("Data de criação da unidade");

                    b.Property<DateTime?>("DataUltimaModificacao")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("UND_DATA_ULTIMA_MODIFICACAO")
                        .HasColumnOrder(6)
                        .HasDefaultValueSql("GETDATE()")
                        .HasComment("Data da última modificação da unidade");

                    b.Property<bool?>("Excluido")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("UND_EXCLUIDO")
                        .HasColumnOrder(7)
                        .HasComment("Flag que indica se a unidade foi excluída");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("UND_NUMERO")
                        .HasColumnOrder(3)
                        .HasComment("Número da unidade");

                    b.HasKey("Id")
                        .HasName("PK_UNIDADES");

                    b.HasIndex("CondominioId", "Numero", "Bloco")
                        .IsUnique()
                        .HasDatabaseName("IX_UNIDADES_CONDOMINIO_NUMERO_BLOCO")
                        .HasFilter("[UND_BLOCO] IS NOT NULL");

                    b.ToTable("TB_UNIDADES", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("e42af47c-24c2-4f83-a8cb-3cc95213ddc6"),
                            Bloco = "A",
                            CondominioId = new Guid("e4e6af8b-8588-438b-9750-c45227c3aa92"),
                            DataCriacao = new DateTime(2023, 5, 2, 8, 5, 19, 210, DateTimeKind.Local).AddTicks(5832),
                            Numero = "101"
                        });
                });

            modelBuilder.Entity("EntregaSegura.Entities.Models.Endereco", b =>
                {
                    b.HasOne("EntregaSegura.Entities.Models.Condominio", "Condominio")
                        .WithOne("Endereco")
                        .HasForeignKey("EntregaSegura.Entities.Models.Endereco", "CondominioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ENDERECO_CONDOMINIO");

                    b.Navigation("Condominio");
                });

            modelBuilder.Entity("EntregaSegura.Entities.Models.Entrega", b =>
                {
                    b.HasOne("EntregaSegura.Entities.Models.Funcionario", "Funcionario")
                        .WithMany("Entregas")
                        .HasForeignKey("FuncionarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_FUNCIONARIO_ENTREGA");

                    b.HasOne("EntregaSegura.Entities.Models.Morador", "Morador")
                        .WithMany("Entregas")
                        .HasForeignKey("MoradorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_MORADORES_ENTREGAS");

                    b.HasOne("EntregaSegura.Entities.Models.Transportadora", "Transportadora")
                        .WithMany("Entregas")
                        .HasForeignKey("TransportadoraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ENTREGA_TRANSPORTADORA");

                    b.HasOne("EntregaSegura.Entities.Models.Unidade", "Unidade")
                        .WithMany("Entregas")
                        .HasForeignKey("UnidadeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ENTREGAS_UNIDADES");

                    b.Navigation("Funcionario");

                    b.Navigation("Morador");

                    b.Navigation("Transportadora");

                    b.Navigation("Unidade");
                });

            modelBuilder.Entity("EntregaSegura.Entities.Models.Funcionario", b =>
                {
                    b.HasOne("EntregaSegura.Entities.Models.Condominio", "Condominio")
                        .WithMany("Funcionarios")
                        .HasForeignKey("CondominioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_FUNCIONARIO_CONDOMINIO");

                    b.Navigation("Condominio");
                });

            modelBuilder.Entity("EntregaSegura.Entities.Models.Morador", b =>
                {
                    b.HasOne("EntregaSegura.Entities.Models.Unidade", "Unidade")
                        .WithMany("Moradores")
                        .HasForeignKey("UnidadeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_MORADORES_UNIDADES");

                    b.Navigation("Unidade");
                });

            modelBuilder.Entity("EntregaSegura.Entities.Models.Unidade", b =>
                {
                    b.HasOne("EntregaSegura.Entities.Models.Condominio", "Condominio")
                        .WithMany("Unidades")
                        .HasForeignKey("CondominioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_UNIDADES_CONDOMINIOS");

                    b.Navigation("Condominio");
                });

            modelBuilder.Entity("EntregaSegura.Entities.Models.Condominio", b =>
                {
                    b.Navigation("Endereco");

                    b.Navigation("Funcionarios");

                    b.Navigation("Unidades");
                });

            modelBuilder.Entity("EntregaSegura.Entities.Models.Funcionario", b =>
                {
                    b.Navigation("Entregas");
                });

            modelBuilder.Entity("EntregaSegura.Entities.Models.Morador", b =>
                {
                    b.Navigation("Entregas");
                });

            modelBuilder.Entity("EntregaSegura.Entities.Models.Transportadora", b =>
                {
                    b.Navigation("Entregas");
                });

            modelBuilder.Entity("EntregaSegura.Entities.Models.Unidade", b =>
                {
                    b.Navigation("Entregas");

                    b.Navigation("Moradores");
                });
#pragma warning restore 612, 618
        }
    }
}
